### ISSUE TITLE
"Error: Room released before initialization started" when using "@ably/chat/react" providers in my nextjs app.

### ISSUE THREAD

**Issue by harrisrobin** [ably/ably-chat-js#350]
I have the following layout.tsx:

```tsx
// layout.tsx
import { LobbyRoomProvider } from "@/app/[locale]/(dynamic)/cs/lobby/[room]/_components/lobby-room-provider"
import { getAuthUser } from "@repo/supabase/queries"

interface LobbyLayoutProps {
  children: React.ReactNode
  params: {
    room: string
  }
}
export default async function LobbyLayout({
  children,
  params,
}: LobbyLayoutProps) {
  const { room } = params
  const { data } = await getAuthUser()
  const user = data?.user
  return (
    <LobbyRoomProvider initialRoom={room} initialUser={user}>
      {children}
    </LobbyRoomProvider>
  )
}
```

I then have the following client component which has the ably providers and so on:
```tsx
// lobby-room-provider.tsx
"use client"
import * as Ably from "ably"
import { ChatClientProvider, ChatRoomProvider } from "@ably/chat/react"
import { ChatClient, LogLevel, RoomOptionsDefaults } from "@ably/chat"
import { useMemo } from "react"
import { useUser } from "@supabase/auth-helpers-react"
import type { User } from "@supabase/supabase-js"

interface LobbyRoomProviderProps {
  children: React.ReactNode
  initialUser: User | null
  initialRoom: string
}
export function LobbyRoomProvider(props: LobbyRoomProviderProps) {
  const { children, initialUser, initialRoom } = props
  const clientUser = useUser()
  const user = clientUser ?? initialUser
  const ablyChatRoom = `lobby:${initialRoom}`

  const isLoggedIn = !!user

  const client = useMemo(() => {
    return new Ably.Realtime({
      authUrl: isLoggedIn ? "/api/ably" : undefined,
      autoConnect: typeof window !== "undefined",
      clientId: isLoggedIn ? user.id : undefined,
      key: process.env.NEXT_PUBLIC_ABLY_API_KEY,
      logHandler: console.log,
      logLevel: 2,
    })
  }, [user, isLoggedIn])

  const chatClient = useMemo(() => {
    return new ChatClient(client, {
      logLevel: LogLevel.Info,
      logHandler: console.log,
    })
  }, [client])

  return (
    <ChatClientProvider client={chatClient}>
      <ChatRoomProvider id={ablyChatRoom} options={RoomOptionsDefaults}>
        {children}
      </ChatRoomProvider>
    </ChatClientProvider>
  )
}
```

Loading the app gives me this error immediately:
![CleanShot 2024-09-17 at 19 08 36@2x](https://github.com/user-attachments/assets/5dc3dc8b-4080-4852-8e8a-8319c66a3f4d)

My logs also show the following error:

```
Ably: Channel state for channel "lobby:1::$chat::$reactions": detached; reason: [_ErrorInfo: Channel detached; statusCode=404; code=90001] 2

```

I was under the impression that it would create the channel for me if it does not exist. Is that not correct?

**Comment by harrisrobin** [comment]
It does look like the chat works despite this error that you get, but would be nice to know how to not get the error.

**Comment by AndyTWF** [comment]
Hi @harrisrobin,

Thanks for raising! It appears to be due to a race condition (along with an unhandled promise rejection) somewhere in the room initialisation process. My guess is that it's probably related to React's strict mode and the fact it spins everything up and then tears it down again in quick succession. I've managed to recreate it locally, but it's intermittent for sure.

You're right that Chat should work despite this error - as it's an error that's generated by an artefact that's in the process of being cleaned up. Nevertheless, appreciate it's confusing and frustrating when it pops up - so we'll take a look into this!

**Comment by AndyTWF** [comment]
Hi again @harrisrobin! Version 0.2.1 of the SDK has now been released which should resolve the issue you described. Please let me know if you experience any further issues!
