### ISSUE TITLE
Cannot read property 'Suspended' of undefined when trying to use it in React Native (Expo)

### ISSUE THREAD

**Issue by harrisrobin** [ably/ably-chat-js#381]
Hi, 

I'm trying to use ably-chat-js in a react-native (expo) app and I run into the following:
![CleanShot 2024-10-27 at 23 08 50@2x](https://github.com/user-attachments/assets/1c6c808f-362b-4a8e-a4c8-cc3d7393d867)

```ts
//ably.ts
import { ChatClient } from '@ably/chat'
import * as Ably from 'ably'

enum AblyLogLevel {
  Silent = 0,
  Error = 1,
  All = 2,
}

const ablyRealtime = new Ably.Realtime({
  authUrl: `${process.env.EXPO_PUBLIC_NEXT_API_URL}/api/auth/ably`,
  key: process.env.EXPO_PUBLIC_ABLY_API_KEY,
  logHandler: console.log,
  logLevel: AblyLogLevel.Silent,
})

const ablyChatClient = new ChatClient(ablyRealtime)

export { ablyRealtime, ablyChatClient }

```

and I am simply importing the ablyChatClient and trying to get a room with:
```ts
  useEffect(() => {
    const room = ablyChatClient.rooms.get(
      'basketball-stream',
      RoomOptionsDefaults,
    )
    console.log('room', room)
  }, [])
```

. We also use ably-js in react web with no issue so this seems to be specific to React Native somehow. 

Using ably/react has the same result.

Any ideas @AndyTWF ?

Thank you

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/CHA-728) by [Unito](https://www.unito.io)

**Comment by AndyTWF** [comment]
Hi @harrisrobin!

I suspect this might be down to Metro's module resolution. For both chat and also ably/react, we use `exports` in `package.json` so that the paths are distinguishable.

This isn't a default setting in Metro, so needs to be added to `metro.config.js`, as an example:

```ts
const { getDefaultConfig } = require("expo/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  ...defaultConfig,
  resolver: {
    ...defaultConfig.resolver,
    unstable_enablePackageExports: true, // Enable 'exports' field in package.json,
  },
};
```

Does this work for you? If so, I'll update the README with an extra setup step!

**Comment by AndyTWF** [comment]
This issue has been quiet for a few weeks, so I will close it for now. We've now added some React Native specific guidance to the `README` and website documentation on how to handle imports.

Please re-open this issue if anything comes up, and thanks for the report!
