### ISSUE TITLE
[CHA-RL3j] RoomlifecycleManager, release room when in initialized state

### ISSUE THREAD

**Issue by sacOO7** [ably/ably-chat-js#398]
- Currently, roomlifecyclemanager.ts doesn't check for initialized state for release OP.
https://github.com/ably/ably-chat-js/blob/0e1b52336a9e15c711d62848a0c3ba841dc6ae77/src/core/room-lifecycle-manager.ts#L793
can be updated to 
```
if (this._lifecycle.status === RoomStatus.Detached || this._lifecycle.status === RoomStatus.Initialized)
```
- Add test for the same

**Comment by AndyTWF** [comment]
This is actually a bug, but for a different reason. By just setting the room to `released`, we're actually causing a channel leak, so we'll need to fix this.

**Comment by AndyTWF** [comment]
Good spot!

**Comment by AndyTWF** [comment]
Created https://ably.atlassian.net/browse/CHA-716 to fix both the spec and the implementation
