### ISSUE TITLE
[RoomLifeCycleManager] `_operationInProgress` flag incorrectly set

### ISSUE THREAD

**Issue by sacOO7** [ably/ably-chat-js#406]
- Currently, `operationInProgress` flag is [set to false only when `attach` operation finishes.](https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/room-lifecycle-manager.ts#L592) 
- It should be set `false` at the end of other operations like `Detach`, `Release`, and `Internal` operations.
- Also, not sure if we really need this code snippet in place 
https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/room-lifecycle-manager.ts#L130-L134
- This sets `operationInProgress` to `true` when the room has just initialized and not performing any operation.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/CHA-723) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Also, I feel `operationInProgress` should be set to `false` at the end of `mtx` promise, not in between right? 
Like in case of `Attach` op, it's set in between, 
https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/room-lifecycle-manager.ts#L592-L600
While we are still emitting `discontinuity` events as a part of mutually exclusive/atomic attach op.

**Comment by sacOO7** [comment]
I mean, the flag can be simply set to `true` before starting `mtx` and set to `false` after `mtx` op ends.

**Comment by sacOO7** [comment]
Btw, if `operationInProgress` is only meant for `Attach` op, we should update doc + variable name for the same.

**Comment by AndyTWF** [comment]
Yep - agree this needs a re-look.

The main purpose of the flag is to prevent channel events from being considered during operations.

Re the positioning of the set to `false` - where it happens should be fine practically, but no harm moving it to before the return.

**Comment by sacOO7** [comment]
Hey, I didn't want to block you for PR related to this, but I didn't really get what you meant by
https://github.com/ably/ably-chat-js/pull/412#issuecomment-2490954146
> The place I don't think it works is in the attach cycle - the attach operation ends (and should fail fast back to the user), but we need to continue the lifecycle operation in the background to retry, so in this instance we don't want to tie the lifecycle op to the attach call but to what happens in the background afterwards.

In simple terms, what I understand is `operationInProgress=true` if there is ongoing operations or pending operations. When all operations all performed, ``operationInProgress=false`, is that right?

**Comment by sacOO7** [comment]
Basically, we should wait for all operations to be performed, then only set `operationInProgress = false` right?
