### ISSUE TITLE
[CHA-RL5a1] Ignore suspended channel during channel windDown operation

### ISSUE THREAD

**Issue by sacOO7** [ably/ably-chat-js#407]
- As per CHA-RL5a1, As many chat features share channels, the equality of contributors when deciding not to detach is based on their realtime channel, and not the contributor themselves. i.e. if two features share a realtime channel, and that channel is suspended, then that channel should not be detached.
- So, following code snippet should be updated from
https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/room-lifecycle-manager.ts#L630-L637

to

```
    if (contributor.channel === except?.channel && this._lifecycle.status !== RoomStatus.Failed) {
      return;
    }
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/CHA-722) by [Unito](https://www.unito.io)

**Comment by AndyTWF** [comment]
Thanks! We've got this one covered already on https://ably.atlassian.net/browse/CHA-700
